-- Fix final callback node in N8N workflow
UPDATE workflow_entity
SET nodes = jsonb_set(
  nodes::jsonb,
  '{4, parameters, functionCode}',
  '"// ========================\n// NODE 4: FINAL RESULT CALLBACK (Fixed to match backend contract)\n// ========================\n\nconst result = $input.item.json;\nconst trace = result.trace;\n\nconsole.log(''[N8N_CALLBACK_FINAL] Sending final result'');\n\n// Calculate execution time (assume 5 seconds for simulation)\nconst executionTime = 5.0;\n\n// Transform results to match backend contract\nconst actionsPerformed = result.results\n  .filter(r => r.status === ''success'')\n  .map(r => r.step_id.toString());\n\nconst errors = result.results\n  .filter(r => r.status === ''failed'')\n  .map(r => ({\n    step_id: r.step_id,\n    error_message: r.error || ''Unknown error''\n  }));\n\n// Prepare payload matching backend''s N8NWorkflowResult model\nconst callbackPayload = {\n  thought_stream_id: trace.thought_stream_id,\n  workflow_name: ''emergency_water_leak'',\n  status: result.status,  // ''success'' or ''failed''\n  execution_time: executionTime,\n  result: {\n    steps_executed: result.results.length,\n    steps_failed: result.failed_count,\n    actions_performed: actionsPerformed,\n    errors: errors.length > 0 ? errors : undefined\n  },\n  metadata: {\n    request_id: result.request_id,\n    workflow_type: result.workflow_type,\n    success_count: result.success_count,\n    skipped_count: result.skipped_count\n  },\n  error: result.status === ''failed'' ? ''Critical step failed'' : null\n};\n\nconsole.log(''[N8N_CALLBACK_PAYLOAD]'', JSON.stringify(callbackPayload, null, 2));\n\n// Send final result callback (best effort)\ntry {\n  await $http.request({\n    method: ''POST'',\n    url: ''http://backend:8000/api/n8n/callback/workflow-result'',\n    headers: {\n      ''Authorization'': ''Bearer disruptiq_n8n_webhook_secret_2024_secure_token'',\n      ''Content-Type'': ''application/json''\n    },\n    body: callbackPayload,\n    timeout: 3000\n  });\n  console.log(''[N8N_CALLBACK_FINAL_OK]'');\n} catch (error) {\n  console.error(''[N8N_CALLBACK_FINAL_FAIL]'', error.message);\n}\n\nconsole.log(''[N8N_END] Workflow complete'');\n\nreturn {\n  json: {\n    success: true,\n    result: result\n  }\n};"'::jsonb
)::json,
"updatedAt" = CURRENT_TIMESTAMP
WHERE name = 'emergency-water-leak';
