import React, { useState, useEffect } from 'react';
import { Settings, Bell, Globe, Mail, Database, User, Save, RefreshCw } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';

interface UserSettings {
  // User Preferences
  language: 'fr' | 'en';
  emailNotifications: boolean;
  digestNotifications: boolean;
  urgentEmailAlerts: boolean;

  // Email Settings
  emailSyncFrequency: number; // in minutes
  autoGenerateDigest: boolean;
  digestTime: string; // HH:MM format

  // Display Settings
  compactView: boolean;
  itemsPerPage: number;
  showEmailPreviews: boolean;

  // Account Info
  userName?: string;
  userEmail?: string;
}

const DEFAULT_SETTINGS: UserSettings = {
  language: 'fr',
  emailNotifications: true,
  digestNotifications: true,
  urgentEmailAlerts: true,
  emailSyncFrequency: 60,
  autoGenerateDigest: true,
  digestTime: '08:00',
  compactView: false,
  itemsPerPage: 10,
  showEmailPreviews: true,
};

export const SettingsPage: React.FC = () => {
  const [settings, setSettings] = useState<UserSettings>(DEFAULT_SETTINGS);
  const [hasChanges, setHasChanges] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Load settings from localStorage on mount
  useEffect(() => {
    const savedSettings = localStorage.getItem('disruptiq_settings');
    if (savedSettings) {
      try {
        const parsed = JSON.parse(savedSettings);
        setSettings({ ...DEFAULT_SETTINGS, ...parsed });
      } catch (error) {
        console.error('Failed to parse settings:', error);
      }
    }
  }, []);

  // Update specific setting
  const updateSetting = <K extends keyof UserSettings>(key: K, value: UserSettings[K]) => {
    setSettings(prev => ({ ...prev, [key]: value }));
    setHasChanges(true);
  };

  // Save settings
  const handleSave = async () => {
    setIsSaving(true);
    const toastId = toast.loading('Sauvegarde des paramètres...');

    try {
      // Save to localStorage (backend API can be added later)
      localStorage.setItem('disruptiq_settings', JSON.stringify(settings));

      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 500));

      setHasChanges(false);
      toast.success('✅ Paramètres sauvegardés avec succès!', { id: toastId });
    } catch (error) {
      console.error('Failed to save settings:', error);
      toast.error('Erreur lors de la sauvegarde', { id: toastId });
    } finally {
      setIsSaving(false);
    }
  };

  // Reset to defaults
  const handleReset = () => {
    if (window.confirm('Êtes-vous sûr de vouloir réinitialiser tous les paramètres ?')) {
      setSettings(DEFAULT_SETTINGS);
      setHasChanges(true);
      toast.info('Paramètres réinitialisés (pensez à sauvegarder)');
    }
  };

  // Clear cache
  const handleClearCache = () => {
    if (window.confirm('Êtes-vous sûr de vouloir vider le cache local ?')) {
      const settingsBackup = localStorage.getItem('disruptiq_settings');
      localStorage.clear();
      if (settingsBackup) {
        localStorage.setItem('disruptiq_settings', settingsBackup);
      }
      toast.success('Cache vidé avec succès');
      window.location.reload();
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-2">
            <Settings className="h-8 w-8" />
            Configuration
          </h1>
          <p className="text-gray-500 mt-1">
            Personnalisez votre expérience DisruptIQ
          </p>
        </div>

        {hasChanges && (
          <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-300">
            Modifications non sauvegardées
          </Badge>
        )}
      </div>

      {/* Save/Reset Actions */}
      {hasChanges && (
        <Card className="bg-blue-50 border-blue-200">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <p className="text-sm text-blue-900">
                Vous avez des modifications non sauvegardées
              </p>
              <div className="flex gap-2">
                <Button variant="outline" onClick={handleReset} size="sm">
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Réinitialiser
                </Button>
                <Button onClick={handleSave} disabled={isSaving} size="sm">
                  <Save className="h-4 w-4 mr-2" />
                  {isSaving ? 'Sauvegarde...' : 'Sauvegarder'}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* User Preferences */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <User className="h-5 w-5" />
            Préférences utilisateur
          </CardTitle>
          <CardDescription>
            Configuration de votre compte et préférences personnelles
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Language */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium flex items-center gap-2">
                <Globe className="h-4 w-4" />
                Langue de l'interface
              </label>
              <p className="text-xs text-gray-500">
                Langue d'affichage de l'application
              </p>
            </div>
            <select
              value={settings.language}
              onChange={(e) => updateSetting('language', e.target.value as 'fr' | 'en')}
              className="border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="fr">Français</option>
              <option value="en">English</option>
            </select>
          </div>

          {/* Compact View */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Mode compact
              </label>
              <p className="text-xs text-gray-500">
                Afficher plus d'éléments par page
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.compactView}
              onChange={(e) => updateSetting('compactView', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>

          {/* Items per page */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Éléments par page
              </label>
              <p className="text-xs text-gray-500">
                Nombre d'éléments affichés dans les listes
              </p>
            </div>
            <select
              value={settings.itemsPerPage}
              onChange={(e) => updateSetting('itemsPerPage', parseInt(e.target.value))}
              className="border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value={5}>5</option>
              <option value={10}>10</option>
              <option value={20}>20</option>
              <option value={50}>50</option>
            </select>
          </div>

          {/* Show Email Previews */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Aperçu des emails
              </label>
              <p className="text-xs text-gray-500">
                Afficher un extrait du contenu des emails
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.showEmailPreviews}
              onChange={(e) => updateSetting('showEmailPreviews', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>
        </CardContent>
      </Card>

      {/* Notification Settings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bell className="h-5 w-5" />
            Notifications
          </CardTitle>
          <CardDescription>
            Gérez les notifications et alertes
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Email Notifications */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Notifications par email
              </label>
              <p className="text-xs text-gray-500">
                Recevoir des notifications par email
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.emailNotifications}
              onChange={(e) => updateSetting('emailNotifications', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>

          {/* Digest Notifications */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Notifications de digest
              </label>
              <p className="text-xs text-gray-500">
                Recevoir une notification lors de la génération du digest quotidien
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.digestNotifications}
              onChange={(e) => updateSetting('digestNotifications', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>

          {/* Urgent Email Alerts */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Alertes emails urgents
              </label>
              <p className="text-xs text-gray-500">
                Recevoir une alerte immédiate pour les emails marqués urgents
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.urgentEmailAlerts}
              onChange={(e) => updateSetting('urgentEmailAlerts', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>
        </CardContent>
      </Card>

      {/* Email & Digest Settings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Mail className="h-5 w-5" />
            Emails & Digest
          </CardTitle>
          <CardDescription>
            Configuration de la synchronisation et du digest quotidien
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Email Sync Frequency */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Fréquence de synchronisation
              </label>
              <p className="text-xs text-gray-500">
                Intervalle de vérification des nouveaux emails
              </p>
            </div>
            <select
              value={settings.emailSyncFrequency}
              onChange={(e) => updateSetting('emailSyncFrequency', parseInt(e.target.value))}
              className="border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value={15}>Toutes les 15 minutes</option>
              <option value={30}>Toutes les 30 minutes</option>
              <option value={60}>Toutes les heures</option>
              <option value={120}>Toutes les 2 heures</option>
              <option value={240}>Toutes les 4 heures</option>
            </select>
          </div>

          {/* Auto Generate Digest */}
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <label className="text-sm font-medium">
                Génération automatique du digest
              </label>
              <p className="text-xs text-gray-500">
                Générer automatiquement le digest quotidien
              </p>
            </div>
            <input
              type="checkbox"
              checked={settings.autoGenerateDigest}
              onChange={(e) => updateSetting('autoGenerateDigest', e.target.checked)}
              className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
          </div>

          {/* Digest Time */}
          {settings.autoGenerateDigest && (
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <label className="text-sm font-medium">
                  Heure de génération du digest
                </label>
                <p className="text-xs text-gray-500">
                  Heure quotidienne de génération automatique
                </p>
              </div>
              <input
                type="time"
                value={settings.digestTime}
                onChange={(e) => updateSetting('digestTime', e.target.value)}
                className="border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          )}
        </CardContent>
      </Card>

      {/* Data Management */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Database className="h-5 w-5" />
            Gestion des données
          </CardTitle>
          <CardDescription>
            Gestion du cache et des données locales
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
            <div>
              <p className="font-medium text-sm">Cache local</p>
              <p className="text-xs text-gray-600 mt-1">
                Supprime toutes les données mises en cache localement
              </p>
            </div>
            <Button variant="outline" size="sm" onClick={handleClearCache}>
              Vider le cache
            </Button>
          </div>

          <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
            <div>
              <p className="font-medium text-sm">Exporter les paramètres</p>
              <p className="text-xs text-gray-600 mt-1">
                Télécharger une sauvegarde de vos paramètres
              </p>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                const dataStr = JSON.stringify(settings, null, 2);
                const blob = new Blob([dataStr], { type: 'application/json' });
                const url = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = url;
                link.download = 'disruptiq-settings.json';
                link.click();
                toast.success('Paramètres exportés');
              }}
            >
              Exporter
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Bottom Actions */}
      <div className="flex items-center justify-between pt-4 border-t">
        <Button variant="outline" onClick={handleReset}>
          <RefreshCw className="h-4 w-4 mr-2" />
          Réinitialiser tout
        </Button>
        <Button onClick={handleSave} disabled={!hasChanges || isSaving}>
          <Save className="h-4 w-4 mr-2" />
          {isSaving ? 'Sauvegarde...' : 'Sauvegarder les modifications'}
        </Button>
      </div>
    </div>
  );
};
